### ISSUE TITLE
Desktop – Overlay Template

### ISSUE THREAD

**Issue by colinmurphy01** [usdoj-crt/beta-ada#23]
### Context
With initial designs completed, we can develop an initial template for the beta.ada.gov site.

### This issue is done when
- [x] All components are deployed to a branch and a federalist preview link is generated
- [ ] Design has reviewed preview and signed off
- [x] An accessibility review has been conducted?
- [ ] Kristin has reviewed and signed off
- [x] PR has been submitted and is ready for production

**Comment by hursey013** [comment]
Fixed with https://github.com/usdoj-crt/beta-ada/pull/60

Preview link: https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/site/usdoj-crt/beta-ada/understanding/parking/
