### ISSUE TITLE
Beta.ada.gov Header & Footer

### ISSUE THREAD

**Issue by colinmurphy01** [usdoj-crt/beta-ada#24]
### Context
With [initial designs completed](https://drive.google.com/file/d/1-OTnPTG2b_Joys0Ry0BsrVE-bd0lUva_/view?usp=sharing), we can develop an initial header and footer for the beta.ada.gov site.

### This issue is done when
- [ ] Header and Footer are deployed to a branch and a federalist preview link is generated
- [ ] Design has reviewed preview and signed off
- [ ] An accessibility review has been conducted?
- [ ] Kristin has reviewed and signed off
- [ ] PR has been submitted and is ready for production

**Comment by hursey013** [comment]
Initial header and footer components completed. Preview link: https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/site/usdoj-crt/beta-ada/
